services:
  web:
    build: .
    container_name: box-check-joy-app
    ports:
      - "52222:80"
    volumes:
      - .:/app
      - /app/node_modules

    restart: unless-stopped

    environment:
      - NODE_ENV=development
